### ISSUE TITLE
New release and tag doesn't let you trigger post terraform-module-releaser actions

### ISSUE THREAD

**Issue by ivangonzalezz** [techpivot/terraform-module-releaser#154]
Hey there!

We've been testing a bit more and we faced with another issue with this action.

We're running the `terraform-module-releaser` action and it creates a new tag and a new release for each module we touch in our repository. What we saw is that the release and the tag are empty and they only contain the content of the module itself. For that reason, we cannot run actions triggered by a new release or a new tag.

In this case, our use case is to publish the released module in another repository, i.e. JFrog Artifactory.

Would be great that the release keeps the module itself as an asset and also all the Source code. That way, the trigger would work. For example, this release from this monorepo: https://github.com/stellar/go/releases/tag/horizon-v22.0.2

What do you think?

TY in advance!!

**Comment by virgofx** [comment]
hi @ivangonzalezz Thanks for providing those details! You're right - this is an important limitation that affects workflows like publishing to Artifactory. The current behavior of only including the specific module's content in the release is intentional (as it helps keep the module source files smaller improving terraform performance which is typically how most large terraform deployments work), but I understand it's not ideal for your use case where you need the complete source context. 

Currently, there are a couple of potential workarounds you could consider:

1. Use git tags instead of releases as your trigger, and have your workflow check out the full repository at that tag (Again, this is the recommended approach. So instead of referencing `source = "../sibling"` you would actually pin your source. It's a topic for a different conversation but an option)
2. Create a composite action that first creates the release and then adds additional assets to it using the GitHub API

However, as mentioned in #144, I'm working on a major version update that will include proper handling of local module dependencies. This would ensure releases contain all necessary context. Would either of those workarounds help in the meantime, or would you prefer to wait for the dependency-aware release?

Let me know if you'd like to discuss the workarounds in more detail!

**Comment by ivangonzalezz** [comment]
Hey @virgofx !

Thank you for those workarounds. About the second one, I'll need some time to see if it helps.

About the first one, I think it doesn't work because when we create the tag with this action, the tag is created only with the context of the module. See this [example](https://github.com/techpivot/terraform-modules-demo/tree/aws/vpc-endpoint/v1.1.3) from the demo repo. So when the tag is created, there is no workflow to be triggered for that tag. Maybe I'm wrong because I'm not an expert on Github Actions.

If I'm right about that, I can try to work with the second workaround or maybe just wait until you complete that major version.

Thanks a lot!!!

**Comment by luis-garza** [comment]
@ivangonzalezz it looks like we're having the same challenges... 😅 

For this scenario, you can solve it by using the job and publishing whatever based in the new [available outputs](https://github.com/techpivot/terraform-module-releaser/issues/24), at that time you'll have the entire repository available... 😬

**Comment by virgofx** [comment]
Hi @ivangonzalezz - After revisiting this, I still don't think it makes sense to store the entire source code of the monorepo as an artifact for each released module. I may not be fully understanding your use case; however, you should be able to on `closed` event (e.g. merge) use the outputs to publish the exact release (can get from the outputs in this event) to a downstream artifactory. 

Can you let me know if 1.7.1 (which has correct outputs) fixes your issue?

**Comment by virgofx** [comment]
Hi @ivangonzalezz Hey @ivangonzalezz — thanks for the continued discussion and apologies for the delayed close.

**This behavior is intentional and by design.** Each module release tag points to a sparse, pruned tree containing only the module's own source files. This is a deliberate choice that keeps module references lightweight — when a consumer pins `source = "git::https://github.com/org/repo//modules/vpc?ref=modules/vpc/v1.2.0"`, Git fetches only what it needs, not the entire monorepo. Bundling the full source tree into every module release would undermine that benefit and balloon every `terraform init`.

**The recommended workaround for downstream publishing (e.g. Artifactory):**

Use the `pull_request` `closed` event on your workflow — this fires after the PR is merged, at which point the full repository checkout is available and all module releases have already been created by `terraform-module-releaser`. You can then consume the action's outputs (`changed-modules-map`, `changed-module-names`, etc.) to iterate over exactly which modules were released and push them to Artifactory:

```yaml
on:
  pull_request:
    types: [closed]

jobs:
  publish-to-artifactory:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@...

      - name: Run terraform-module-releaser
        id: releaser
        uses: techpivot/terraform-module-releaser@...

      - name: Publish released modules to Artifactory
        if: steps.releaser.outputs.changed-module-names != '[]'
        run: |
          # Iterate over changed modules and publish using the full repo checkout
          echo '${{ steps.releaser.outputs.changed-modules-map }}' | jq -r 'keys[]' | while read module; do
            # publish logic here
          done
```

This gives you the full repository context, the exact list of released modules and their new versions, and doesn't require re-designing how releases and tags are structured.

Closing this as **by design** — but please feel free to reopen if there's a scenario the outputs don't cover.
