### ISSUE TITLE
Enhancement: Allow Including/Excluding Directories for Module Discovery

### ISSUE THREAD

**Issue by lapierrejl** [techpivot/terraform-module-releaser#157]
First off, thanks for creating this project! This GitHub Action is a fantastic tool for automating Terraform module releases, and I really appreciate the effort you’ve put into it.

However, I’m currently unable to use it due to a limitation in how modules are detected. Our codebase follows a monorepo structure where we have both Terraform modules and stacks in the same repository. Since the action scans for .tf files in all directories, it ends up trying to release modules from our Terraform stacks, which is not ideal.

Proposed Enhancement
It would be great to have a way to include or exclude specific directories when scanning for Terraform modules. This would allow users to fine-tune which directories should be considered for module releases.

Possibly something like this
```
      - name: Terraform Module Releaser
        uses: techpivot/terraform-module-releaser@v1
        with:
          path-filter: "modules/**,!stacks/**"
```

Contribution
I’d love to contribute to this project! Are there any contribution guidelines or a roadmap I could follow? If this enhancement aligns with your vision, I’d be happy to help implement it.

Thanks again for your work on this! Looking forward to your thoughts.
